### ISSUE TITLE
Move to a bi-weekly schedule?

### ISSUE THREAD

**Issue by jtpio** [voila-dashboards/voila-dashboards.github.io#14]
In [today's meeting](https://voila-dashboards.github.io/2020/01/20/weekly.html), we discussed with @vidartf whether the Voila Weekly should move to a Bi-Weekly schedule, or maybe even a monthly schedule.

This could for example free some space for a potential Jupyter Widgets meeting, which would also be every two weeks or every month (just an idea, but could be useful to have too).

Thoughts?

cc @SylvainCorlay @maartenbreddels @vidartf

**Comment by vidartf** [comment]
👍

**Comment by jtpio** [comment]
@SylvainCorlay would you be able to modify the frequency of the calendar event?

So it correctly shows up on the landing page: https://voila-dashboards.github.io/

We discussed that last week with @aschlaep and moving to a bi-weekly schedule sounds good on his side too.

**Comment by jtpio** [comment]
Closing as fixed.

The voila weekly meeting is now bi-weekly, and alternates with the `ipywidgets` call.

For more info on the Jupyter Community calls: https://discourse.jupyter.org/t/jupyter-community-calendar/2485
